Repository Yonder-Deep/Nautilus, pull requests merged in 2024-11, with the labels that each got.

#116 Fixed setup.sh, added README
  web_app/README.md
  web_app/index.html
  web_app/runapp.bat
  web_app/runapp.sh
  web_app/startup.sh
  web_app/testing.html
Labels: documentation, enhancement

#121 Doc/fix requirements
  auv/requirements.txt
  web_app/README.md
  web_app/requirements.txt
Labels: feature

#125 124/fix-webapp-dependencies
  .gitignore
  web_app/README.md
  web_app/app.py
  web_app/auv_gui/.gitignore
  web_app/auv_gui/README.md
  web_app/auv_gui/eslint.config.js
  web_app/auv_gui/index.html
  web_app/auv_gui/package-lock.json
  web_app/auv_gui/package.json
  web_app/auv_gui/public/favicon.ico
  web_app/auv_gui/public/index.html
  web_app/auv_gui/public/logo192.png
  web_app/auv_gui/public/logo512.png
  web_app/auv_gui/public/manifest.json
  web_app/auv_gui/public/robots.txt
  web_app/auv_gui/public/vite.svg
  web_app/auv_gui/src/App.jsx
  web_app/auv_gui/src/index.jsx
  web_app/auv_gui/src/main.jsx
  web_app/auv_gui/tsconfig.json
  web_app/auv_gui/vite.config.js
  web_app/startup.sh
Labels: maintenance

#126 122/Migrate-to-Serve-React-on-FastAPI
  .gitignore
  web_app/README.md
  web_app/app.py
  web_app/auv_gui/index.html
  web_app/auv_gui/package-lock.json
  web_app/auv_gui/package.json
  web_app/auv_gui/public/vite.svg
  web_app/auv_gui/public/yonder_logo.ico
  web_app/auv_gui/src/App.jsx
  web_app/auv_gui/src/components/Test.jsx
  web_app/build.sh
  web_app/startup.sh
Labels: enhancement

#128 GUI rewrite with react only
  .gitignore
  .vscode/settings.json
  web_app/app.py
  web_app/auv_gui/index.html
  web_app/auv_gui/package-lock.json
  web_app/auv_gui/package.json
  web_app/auv_gui/src/components/Test.jsx
  web_app/auv_gui/src/index.jsx
  web_app/auv_gui/src/main.jsx
  web_app/build.sh
  web_app/frontend_gui/.gitignore
  web_app/frontend_gui/README.md
  web_app/frontend_gui/eslint.config.js
  web_app/frontend_gui/index.html
  web_app/frontend_gui/package-lock.json
  web_app/frontend_gui/package.json
  web_app/frontend_gui/public/tests.css
  web_app/frontend_gui/public/yonder_logo.ico
  web_app/frontend_gui/src/main.jsx
  web_app/frontend_gui/src/pages/AutoNav.jsx
  web_app/frontend_gui/src/pages/Tests.jsx
  web_app/frontend_gui/src/pages/components/Forms.jsx
  web_app/frontend_gui/vite.config.js
  web_app/package-lock.json
  web_app/requirements.txt
Labels: feature
